### PR TITLE
MailKit target netstandard1.4

### PR DESCRIPTION
**Pull request by Lisaj**

### CODE REVIEW

**Comment by jstedfast** [comment]
why not netstandard1.3?

**Comment by Lisaj** [comment]
MimeKit is netstandard1.4 cant by lower

**Comment by jstedfast** [comment]
I've targeted 1.3 instead.

**Comment by jstedfast** [comment]
I've just released MimeKit and MailKit 1.4.0 which target netstandard1.3 - thanks for showing me I was wrong about which netstandard I was targeting originally :)

**Pull request closed without merging**
